### ISSUE TITLE
set_preferences! does not remove from __clear__

### ISSUE THREAD

**Issue by pazner** [JuliaPackaging/Preferences.jl#19]
Running
```julia
set_preferences!(Preferences, "a" => nothing; force=true)
set_preferences!(Preferences, "a" => "b"; force=true)
```
results in LocalPreferences.toml
```toml
[Preferences]
__clear__ = ["a"]
a = "b"
```

I would expect that the second call to `set_preferences!` would completely undo the effect of the first call. Is this the intended behavior?
