### ISSUE TITLE
Top level preferences for applications

### ISSUE THREAD

**Issue by 3f6a** [JuliaPackaging/Preferences.jl#65]
I think it would be nice to be able to set preferences for Applications (as opposed to packages). Could that make sense?

Since Applications do not have name or uuids (not necessarily), these preferences could be stored at the top level of the LocalPreferences.toml file, and be associated to the current leaf project. We could set/get them by unqualified `set_preferences!(key => value)` and `get_preferences(key)` (without having to specify UUID or a package name).

```toml
APP_KEY1 = "value1" # current app preferences

[PkgA] # package specific preferences
CONF_PKG_A_KEY1 = "abc"

# ...
```
